### ISSUE TITLE
Zero-alloc parsing

### ISSUE THREAD

**Issue by UkoeHB** [TimJentzsch/bevy_mod_bbcode#14]
Currently `parse_bbcode` requires allocations. Can you add a new function that uses [fold_many0](https://docs.rs/nom/7.1.3/nom/multi/fn.fold_many0.html) to avoid allocations if possible?

It would also be cool if `BbcodeNode` could store `&str` refs, or if you could add a non-allocating parsing path.

**Comment by TimJentzsch** [comment]
Thanks for opening this, improving performance is definitely something I'd like to look into :)
